/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jpa.hibernate.BookManagement;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
